version: "3.8"

services:
  geth:
    # イメージを指定
    image: ethereum/client-go:v1.13.5
    restart: unless-stopped
    ports:
      - 30303:30303
      - 30303:30303/udp
      - 8545:8545
      - 8546:8546
    #  作業ボリュームの指定
    volumes:
      - ${GETH_DATADIR:-/data/geth}:/data
    stop_grace_period: 2m
    healthcheck:
      test: ["CMD-SHELL", "geth attach --datadir /data --exec eth.blockNumber"]
      interval: 10s
      timeout: 5s
      retries: 5
    # コマンドにつけるオプション
    command:
      - --sepolia
      - --datadir=/data
      - --http
      - --http.api=eth,net,web3
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --ws
      - --ws.origins=*
      - --ws.addr=0.0.0.0
      - --ws.api=eth,net,web3
      - --graphql
      - --graphql.corsdomain=*
      - --graphql.vhosts=*
      - --rpc 
      - --rpcapi personal,eth 
      - --dev
    logging:
      driver: json-file
      options:
        max-size: 2m
        max-file: 10
  genesis:
    image: alpine:latest
    restart: on-failure
    entrypoint: ["sh", "-c"]
    command:
      - "if [ ! -f genesis.ssz ]; then wget 'https://github.com/eth-clients/merge-testnets/raw/main/sepolia/genesis.ssz'; fi"
    working_dir: /genesis
    volumes:
      - ${PRYSM_DATADIR:-/data/prysm}:/genesis